Repository streamnative/pulsar-io-sqs, pull requests merged in 2022-05, with the labels that each got.

#368 fix invalid check
  src/main/java/org/apache/pulsar/ecosystem/io/sqs/SQSRecord.java
Labels: doc-info-missing

#370 Use bytes schema for SQS
  src/main/java/org/apache/pulsar/ecosystem/io/sqs/SQSRecord.java
  src/main/java/org/apache/pulsar/ecosystem/io/sqs/SQSSource.java
Labels: doc-info-missing

#373 add aws credential provider docs
  docs/sqs-sink.md
  docs/sqs-source.md
Labels: area/documentation, doc

#381 bump the AWS SDK version to match pulsar-io-aws
  pom.xml
Labels: type/enhancement, no-need-doc
